name: hello-world

on: 
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test


        