name: hello-world

on: 
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install PNPM
        run: curl -fsSL https://get.pnpm.io/install.sh | sh -
          export PATH=$HOME/.local/share/pnpm:$PATH

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test


        